winetricks git 20191224 version (2020-01-28)

diff --git a/winetricks b/winetricks
--- a/winetricks
+++ b/winetricks
@@ -7944,6 +7944,25 @@ load_dxvk151()
     helper_dxvk_d9vk "$file1" "4.20" "1.1.113" "dxgi,d3d9,d3d10,d3d11"
 }
 
+w_metadata dxvk152 dlls \
+    title="Vulkan-based D3D9/D3D10/D3D11 implementation for Linux / Wine (1.5.2)" \
+    publisher="Philip Rebohle" \
+    year="2017" \
+    media="download" \
+    file1="dxvk-1.5.2.tar.gz" \
+    installed_file1="$W_SYSTEM32_DLLS_WIN/d3d9.dll" \
+    installed_file1="$W_SYSTEM32_DLLS_WIN/d3d10.dll" \
+    installed_file2="$W_SYSTEM32_DLLS_WIN/d3d10_1.dll" \
+    installed_file3="$W_SYSTEM32_DLLS_WIN/d3d10core.dll" \
+    installed_file4="$W_SYSTEM32_DLLS_WIN/d3d11.dll" \
+    installed_file5="$W_SYSTEM32_DLLS_WIN/dxgi.dll"
+
+load_dxvk152()
+{
+    # https://github.com/doitsujin/dxvk
+    w_download "https://github.com/doitsujin/dxvk/releases/download/v1.5.2/dxvk-1.5.2.tar.gz" 684ba886b5ed922c2417753d8178f923c695258c69cc8f778bb59b99bbf62477
+    helper_dxvk_d9vk "$file1" "4.20" "1.1.113" "dxgi,d3d9,d3d10,d3d11"
+}
 
 #----------------------------------------------------------------
 
@@ -22108,38 +22127,39 @@ winetricks_stats_report()
         *) return;;
     esac
 
-    test -f "$WINETRICKS_WORKDIR"/breadcrumbs || return
+    BREADCRUMBS_FILE="$WINETRICKS_WORKDIR"/breadcrumbs
+    if test -f "$BREADCRUMBS_FILE"; then
+        WINETRICKS_STATS_BREADCRUMBS=$(tr '\012' ' ' < "$BREADCRUMBS_FILE")
+        echo "You opted in, so reporting '$WINETRICKS_STATS_BREADCRUMBS' to the winetricks maintainer so he knows which winetricks verbs get used and which don't.  Use --optout to disable future reports."
 
-    WINETRICKS_STATS_BREADCRUMBS=$(tr '\012' ' ' < "$WINETRICKS_WORKDIR"/breadcrumbs)
-    echo "You opted in, so reporting '$WINETRICKS_STATS_BREADCRUMBS' to the winetricks maintainer so he knows which winetricks verbs get used and which don't.  Use --optout to disable future reports."
+        report="os=$(winetricks_os_description)&winetricks=$WINETRICKS_VERSION&breadcrumbs=$WINETRICKS_STATS_BREADCRUMBS"
+        report="$(echo "$report" | sed 's/ /%20/g')"
 
-    report="os=$(winetricks_os_description)&winetricks=$WINETRICKS_VERSION&breadcrumbs=$WINETRICKS_STATS_BREADCRUMBS"
-    report="$(echo "$report" | sed 's/ /%20/g')"
+        # Just do a HEAD request with the raw command line.
+        # Yes, this can be fooled by caches.  That's ok.
 
-    # Just do a HEAD request with the raw command line.
-    # Yes, this can be fooled by caches.  That's ok.
-
-    # Note: these downloads are expected to fail (the resource won't exist), so don't use w_try and use '|| true' to ignore the expected errors
-    if [ "${WINETRICKS_DOWNLOADER}" = "wget" ] ; then
-        $torify wget --timeout "${WINETRICKS_DOWNLOADER_TIMEOUT}" \
-            --tries "$WINETRICKS_DOWNLOADER_RETRIES" \
-            --spider "http://kegel.com/data/winetricks-usage?$report" > /dev/null 2>&1 || true
-    elif [ "${WINETRICKS_DOWNLOADER}" = "curl" ] ; then
-        $torify curl --connect-timeout "${WINETRICKS_DOWNLOADER_TIMEOUT}" \
-           --retry "$WINETRICKS_DOWNLOADER_RETRIES" \
-           -I "http://kegel.com/data/winetricks-usage?$report" > /dev/null 2>&1 || true
-    elif [ "${WINETRICKS_DOWNLOADER}" = "aria2c" ] ; then
-        $torify aria2c $aria2c_torify_opts \
-                $aria2c_torify_opts \
-                --connect-timeout="${WINETRICKS_DOWNLOADER_TIMEOUT}" \
-                --daemon=false \
-                --enable-rpc=false \
-                --input-file='' \
-                --max-tries="$WINETRICKS_DOWNLOADER_RETRIES" \
-                --save-session='' \
-                "http://kegel.com/data/winetricks-usage?$report" > /dev/null 2>&1 || true
-    else
-        w_die "Here be dragons"
+        # Note: these downloads are expected to fail (the resource won't exist), so don't use w_try and use '|| true' to ignore the expected errors
+        if [ "${WINETRICKS_DOWNLOADER}" = "wget" ] ; then
+            $torify wget --timeout "${WINETRICKS_DOWNLOADER_TIMEOUT}" \
+                --tries "$WINETRICKS_DOWNLOADER_RETRIES" \
+                --spider "http://kegel.com/data/winetricks-usage?$report" > /dev/null 2>&1 || true
+        elif [ "${WINETRICKS_DOWNLOADER}" = "curl" ] ; then
+            $torify curl --connect-timeout "${WINETRICKS_DOWNLOADER_TIMEOUT}" \
+            --retry "$WINETRICKS_DOWNLOADER_RETRIES" \
+            -I "http://kegel.com/data/winetricks-usage?$report" > /dev/null 2>&1 || true
+        elif [ "${WINETRICKS_DOWNLOADER}" = "aria2c" ] ; then
+            $torify aria2c $aria2c_torify_opts \
+                    $aria2c_torify_opts \
+                    --connect-timeout="${WINETRICKS_DOWNLOADER_TIMEOUT}" \
+                    --daemon=false \
+                    --enable-rpc=false \
+                    --input-file='' \
+                    --max-tries="$WINETRICKS_DOWNLOADER_RETRIES" \
+                    --save-session='' \
+                    "http://kegel.com/data/winetricks-usage?$report" > /dev/null 2>&1 || true
+        else
+            w_die "Here be dragons"
+        fi
     fi
 }
 
