addition & bug fixes, v0.99.6

diff --git a/winestarter b/winestarter
--- a/winestarter
+++ b/winestarter
@@ -37,6 +37,7 @@ cab_bin=$(find /usr/{bin,local/bin} -name cabextract)
 
 wine_bin='wine'
 wineboot_bin='wineboot'
+wineserver_bin='wineserver'
 conf=$1
 
 ## create the user script conf directory if it doesn't exist
@@ -138,7 +139,6 @@ fn_regedit(){
 		
 		if [ $(diff -q $previous_reg $new_reg| grep -c .) -gt 0 ]; then
 			if [ $(cat $user_prefix/$bottle_prefix/$reg_file.new| grep -c .) -gt 0 ]; then
-#				$wine_bin regedit -D HKEY_CURRENT_USER\\Software\\Wine\\Direct3D
 				printf "REGEDIT4\n\n$user_reg\n" > $user_prefix/$bottle_prefix/$reg_file			
 				$wine_bin regedit $user_prefix/$bottle_prefix/$reg_file
 			else
@@ -202,7 +202,7 @@ fn_reg_dlls(){
 				fi
 			else
 				if [ $reg_elf -gt 0 ]; then	
-					echo "# Wrong system arch. DLLs will by registering to 32bits."
+					echo "# Wrong system arch. DLLs will be registered to 32bits."
 				fi
 				reg_sys=("system32")
 			fi
@@ -252,51 +252,61 @@ fn_use_winepath(){
 	pkg_rel=$(printf $wine_ver| cut -d'-' -f2)
 	
 	download_list(){
-		wget -O $file_temp $dl_address/
-		os_version=$(tac $file_temp | egrep -o "indexcolname.*href=\"[0-9]{2}\/\""| \
-		sed -En "s/^.*([0-9]{2}).*$/\1/p")
-	
-		for os_v in ${os_version[@]}; do
-			wget -O $file_temp.[$os_v] $dl_address/$os_v/$http_elf/
-			dl_bin_list[$os_v]=$(tac $file_temp.[$os_v]| egrep "wine-$hq_stage$b_elf-[0-9]+"| \
-			sed -En "s/^.*$b_elf-([0-9]\.[0-9]*)-([0-9](.rc[0-9])?).$http_elf.*$/\1-\2-$hq_stage,$os_v/p")
-#			sed -En "s/^.*$b_elf-([0-9]\.[0-9]*)-([0-9]).$http_elf.*$/\1-\2-$hq_stage,$os_v/p")
-			if [ $os_v_p ]; then
-				if [ $os_v -ne $os_v_p ]; then
-					new_output=$(echo "${dl_bin_list[$os_v]}"| cut -d',' -f1)
-					prev_output=$(echo "${dl_bin_list[$os_v_p]}"| cut -d',' -f1)
-					_diff=$(echo "$new_output"| grep -vc "$prev_output")
-					if [ $_diff -gt 0 ]; then
-						_added=$(echo "${dl_bin_list[$os_v]}"| grep -v "$prev_output")
-						dl_bin_list[$os_v]=$(echo -e "${dl_bin_list[$os_v_p]}\n$_added")
-						dl_final_list=${dl_bin_list[$os_v]}
+		if [ $wine_pack -gt 0 ]; then
+			wget -O $file_temp $dl_address/
+			os_version=$(tac $file_temp | egrep -o "indexcolname.*href=\"[0-9]{2}\/\""| \
+			sed -En "s/^.*([0-9]{2}).*$/\1/p")
+			for os_v in ${os_version[@]}; do
+				wget -O $file_temp.[$os_v] $dl_address/$os_v/$http_elf/
+				dl_bin_list[$os_v]=$(tac $file_temp.[$os_v]| egrep "wine-$hq_stage$b_elf-[0-9]+"|\
+				sed -En "s/^.*$b_elf-([0-9]\.[0-9]{1,2}(\.[0-9]{1,2})?)-([0-9](.rc[0-9])?).$http_elf.*$/\1-\3-$hq_stage,$os_v/p")
+#				sed -En "s/^.*$b_elf-([0-9]\.[0-9]*)-([0-9](.rc[0-9])?).$http_elf.*$/\1-\2-$hq_stage,$os_v/p")
+	#			sed -En "s/^.*$b_elf-([0-9]\.[0-9]*)-([0-9]).$http_elf.*$/\1-\2-$hq_stage,$os_v/p")
+				if [ $os_v_p ]; then
+					if [ $os_v -ne $os_v_p ]; then
+						new_output=$(echo "${dl_bin_list[$os_v]}"| cut -d',' -f1)
+						prev_output=$(echo "${dl_bin_list[$os_v_p]}"| cut -d',' -f1)
+						_diff=$(echo "$new_output"| grep -vc "$prev_output")
+						if [ $_diff -gt 0 ]; then
+							_added=$(echo "${dl_bin_list[$os_v]}"| grep -v "$prev_output")
+							dl_bin_list[$os_v]=$(echo -e "${dl_bin_list[$os_v_p]}\n$_added")
+							dl_final_list=${dl_bin_list[$os_v]}
+						fi
+						os_v_p=$os_v
 					fi
+				else
 					os_v_p=$os_v
 				fi
-			else
-				os_v_p=$os_v
-			fi
-		done
+			done
+		else
+			wget -O $file_temp $dl_address
+			## limit PoL Wine version list from 1.4 to 1.8.6
+			dl_bin_list=( "$(tac "$file_temp"| cut -d';' -f2| sed -n '/1\.8\.6.*$/,/^1\.4$/p')" )
+		fi
 #		dist_dl_ver=$(echo "$dl_final_list"| grep "$wine_ver"| cut -d',' -f2)
 		echo "$dl_final_list"| grep "$wine_ver"| cut -d',' -f2 > $file_temp.[stamp]
 	}
+	## set Wine binary environment arch.
 	if [ $wine_elf = 1 ]; then ftp_elf='amd64'; b_elf='64'; else ftp_elf='x86'; b_elf=''; fi
-	if ! [ -n $wine_path/$ftp_elf ]; then mkdir -p $HOME/.winebin/$ftp_elf; fi
+	## if system context (distro) is mainly 64bits, prefer to install Wine 64bits packainstead of 32.
+	sys_arch=$(uname -m)
+	if [[ $sys_arch =~ ^.*64 ]]; then
+		ftp_elf='amd64'; b_elf='64'
+	fi
+	## control if wine bin dir exist. If not create it from default
+	if ! [ -n $wine_path/$ftp_elf/ ]; then mkdir -p $HOME/.winebin/$ftp_elf; fi
 	if [ -d $wine_path/$ftp_elf/$wine_ver ]; then
 		_use_winepath_env=1
 	else
 		w_title="Winestarter"
-		
-		## control if wine bin dir exist. If not create it from default
-		if ! [ -d $wine_path/$ftp_elf/ ]; then mkdir -p $wine_path/$ftp_elf; fi
 		## create the download list to fill in the yad loop.
-		if [ $wine_pack = 0 ]; then
-			dl_address_0="http://wine.playonlinux.com/binaries/linux-$ftp_elf"
-			dl_pkg=PlayOnLinux-wine-$wine_ver-linux-$ftp_elf.pol
-			dl_list=( "$dl_address_0/$dl_pkg" )
-			unpack_list=( $dl_pkg )
-		else
-			if [ $wine_elf = 1 ]; then http_elf='x86_64'; b_elf='64'; else http_elf='i686'; b_elf=''; fi
+		if [ $wine_pack -gt 0 ]; then
+#			if [ $wine_elf = 1 ]; then http_elf='x86_64'; b_elf='64'; else http_elf='i686'; b_elf=''; fi
+			if [ $wine_elf = 1 ]; then http_elf='x86_64'; else http_elf='i686'; fi
+			## Check again system arch.
+			if [[ $sys_arch =~ ^.*64 ]]; then
+				http_elf='x86_64'
+			fi
 			if [[ $wine_ver =~ ^.*staging.*$ ]]; then
 				hq_stage='staging'; hq_short='staging'
 			else
@@ -307,21 +317,18 @@ fn_use_winepath(){
 #			else
 #				rc_stage=''
 #			fi
-			file_temp=$(mktemp --tmpdir ftp.XXXXXXXX)
-			dl_address="https://dl.winehq.org/wine-builds/fedora"
+			file_temp=$(mktemp --tmpdir ftp.XXXX)
+			if [ $wine_pack = 2 ]; then dir_ver='wine-builds.old'; else dir_ver='wine-builds'; fi
+			dl_address="https://dl.winehq.org/$dir_ver/fedora"
 			dl_text="$vb\\Building WineHQ packages repository list.$end"
 			
 #			$zen_bin --width=550 --title "$w_title" --window-icon=filesave \
 #			--progress --pulsate --auto-close --no-cancel --text="$dl_text" &
 #			WAIT_UI=$(ps -A | grep "zenity" | awk '{print $1}'| sed -n '1p')
-#			download_list
-			
+#			download_list			
 			download_list | $zen_bin --width=550 --title "$w_title" --text="$dl_text" \
 			--window-icon=filesave --progress --pulsate --auto-close --no-cancel
 			dist_dl_ver=$(cat $file_temp.[stamp])
-			
-#			echo "$dl_final_list"			
-			
 #			dist_dl_ver=$(echo "$dl_final_list"| grep "$wine_ver"| cut -d',' -f2)
 			dl_address_0="$dl_address/$dist_dl_ver/$http_elf"
 			dl_address_1="$dl_address/$dist_dl_ver/i686"
@@ -335,6 +342,11 @@ fn_use_winepath(){
 				"wine-$hq_stage$b_elf-$pkg_ver-$pkg_rel.$http_elf.rpm"
 				"wine-$hq_stage-common-$pkg_ver-$pkg_rel.i686.rpm"
 			)
+		else
+			dl_address_0="http://wine.playonlinux.com/binaries/linux-$ftp_elf"
+			dl_pkg=PlayOnLinux-wine-$wine_ver-linux-$ftp_elf.pol
+			dl_list=( "$dl_address_0/$dl_pkg" )
+			unpack_list=( $dl_pkg )		
 		fi
 		kill $WAIT_UI
 		cd $dl_dir
@@ -364,9 +376,9 @@ fn_use_winepath(){
 			kill $WAIT_UI
 			_use_winepath_env=1
 			else
-				echo -e "»»»» Downloaded package missing. Using defautl Wine."
+				echo -e "»»»» Downloaded package missing. Using defautl Wine if any."
 				if [ $zen_bin ]; then
-					text="$bf\\Downloaded package missing$end$vb.\nUsing system default Wine instead$end"
+					text="$bf\\Downloaded package missing$end$vb.\nUsing system default Wine instead if any.$end"
 					dialog_list="gtk-close;$warning;4;4"; zen_warning
 				fi
 			fi
@@ -380,6 +392,7 @@ fn_use_winepath(){
 #			if [ $b_elf = 64 ]; then ln -sf $wine_path/$ftp_elf/$wine_ver $wine_path/x86/; fi
 			if [ $b_elf = 64 ]; then cd $wine_path/x86; ln -sf ../$ftp_elf/$wine_ver ; fi
 		fi
+		cd $WINEVERPATH/bin
 	fi
 	
 }
@@ -854,7 +867,7 @@ fn_install_exe(){
 				$cmd
 			fi
 			echo "$new_pkg" >> $pkgs_log
-
+			if [ $cd_to = 1 ]; then cd $WINEVERPATH/bin; fi
 		else
 			echo -e "»»»» $new_pkg already installed, pass."
 		fi
@@ -997,28 +1010,6 @@ fn_game_dir_exist(){
 }
 fn_root_key(){
 	## search where is the "Prgram Files" dir and type.
-#	pf_key_yes(){
-#		root_key="Program Files$elf_ext/"
-#		sed_key="Files$elf_ext\/"
-#		win_prog="$root_key"
-##		if [ $special_cmd -gt 0 ]; then
-##			win_prog="Program\ Files$w_elf_ext"
-##		else
-##			win_prog="Program Files$elf_ext\\"
-##		fi
-#	}
-#	pf_key_no(){
-#		root_key=''
-#		sed_key=''
-#		win_prog=''
-#	}
-##	pf_key_maybe(){
-##		root_key=''
-##		sed_key=''
-##		win_prog=''
-##		if ! [ $game_dir ]; then game_dir='null'; fi
-##		if ! [ $game_exe ]; then game_exe='null'; fi
-##	}
 	pf_key_yes(){
 	root_key='Program Files/'
 	sed_key='Files\/'
@@ -1036,10 +1027,6 @@ fn_root_key(){
 		if ! [ $game_dir ]; then game_dir='null'; fi
 	fi
 	if ! [ $game_exe ]; then game_exe='null'; fi
-	## new version
-	
-	
-	
 }
 fn_wine_binary(){
 	if [ $_use_winepath_env -gt 0 ]; then
@@ -1073,6 +1060,7 @@ fn_wine_binary(){
 fn_wineconf(){
 	winecfg
 	perl -ni -pe "s|(w_config)=[0-9]|\1=0|i" $config_file
+	$wineboot_bin -r
 }
 fn_replace_env(){
 	sec_desk=$(find /usr/{bin,local/bin} -name $secondary_desktop)
@@ -1109,6 +1097,41 @@ fn_game_dir_exist
 #fn_extract_lnk
 #exit 0
 fn_convert_desktop_file
+## set windowed mode if checked.
+winestarter_reg=$user_prefix/$bottle_prefix/winestarter.reg
+default_reg=$user_prefix/$bottle_prefix/user.reg
+if [ $windowed -gt 0 ]; then
+	echo "######################## 4"
+#	cd $WINEVERPATH/bin
+#	[[ -s $winestarter_reg ]]|| touch $winestarter_reg	
+	if [[ $(cat $default_reg| egrep -c "\"Desktop\"=\"Default\"") -eq 0 ]]; then
+		## find primary display res.
+		current_res=$(xrandr --current| fgrep "*"| awk '{print $1}')
+		desktop_color='0 0 0'
+		starter_reg="[HKEY_CURRENT_USER\Software\Wine\\\\Explorer]
+\"Desktop\"=\"Default\"
+[HKEY_CURRENT_USER\Software\Wine\\\\Explorer\Desktops]
+\"Default\"=\"$current_res\"
+[HKEY_CURRENT_USER\Control Panel\Colors]
+\"Background\"=\"$desktop_color\""
+		printf "REGEDIT4\n\n$starter_reg\n" > $winestarter_reg
+#		$wine_bin regedit $winestarter_reg
+		if [[ -s $winestarter_reg ]]; then
+			sleep 1
+			$wine_bin regedit $user_prefix/$bottle_prefix/winestarter.reg
+#			$wine_bin regedit winestarter.reg
+			$wineboot_bin -u
+			$wineserver_bin -k
+			
+		fi
+	fi
+else
+	if [[ $(cat $default_reg| egrep -c "\"Desktop\"=\"Default\"") -gt 0 ]]; then
+		$wine_bin regedit -D HKEY_CURRENT_USER\\Software\\Wine\\Explorer
+		$wineboot_bin -e
+	fi
+fi
+#exit 0
 reg_file=$(printf "$conf"| sed -n "s/\.conf//p")".reg"
 ## create and insert registry entry if any.
 #if [[ $(printf "$user_reg"| sed -n '$p') != '' ]]; then fn_regedit; fi
@@ -1142,6 +1165,8 @@ game_exe_only=$(echo "$game_exe"| perl -pe "s/^.*\///p")
 ## execute
 if [ $special_cmd -gt 0 ]; then
 	cd $user_prefix/$bottle_prefix/drive_c/"$root_key"$game_dir
+	## xhange wine_bin to full path
+	wine_bin=$wine_bin_path$wine_bin
 #	$opti_run $wine_bin "$user_prefix/$bottle_prefix/drive_c/"$root_key"$game_dir/$game_exe"
 	$opti_run $wine_bin $game_exe $wine_opts &
 elif [ $start_cmd -gt 0 ]; then
